
export const MOCK_STOCKS = [
  { stockName: 'INFY', symbol: 'INFY.NS', purchasePrice: 1200, quantity: 10, sector: 'Technology', exchange: 'NSE' },
  { stockName: 'TCS', symbol: 'TCS.NS', purchasePrice: 3200, quantity: 5, sector: 'Technology', exchange: 'NSE' },
  { stockName: 'WIPRO', symbol: 'WIPRO.NS', purchasePrice: 400, quantity: 30, sector: 'Technology', exchange: 'NSE' },
  { stockName: 'RELIANCE', symbol: 'RELIANCE.NS', purchasePrice: 2400, quantity: 5, sector: 'Energy', exchange: 'NSE' },
  { stockName: 'ONGC', symbol: 'ONGC.NS', purchasePrice: 180, quantity: 100, sector: 'Energy', exchange: 'NSE' },
  { stockName: 'BPCL', symbol: 'BPCL.NS', purchasePrice: 370, quantity: 25, sector: 'Energy', exchange: 'NSE' },
  { stockName: 'ICICIBANK', symbol: 'ICICIBANK.NS', purchasePrice: 950, quantity: 15, sector: 'Financials', exchange: 'NSE' },
  { stockName: 'HDFCBANK', symbol: 'HDFCBANK.NS', purchasePrice: 1500, quantity: 8, sector: 'Financials', exchange: 'NSE' },
  { stockName: 'AXISBANK', symbol: 'AXISBANK.NS', purchasePrice: 900, quantity: 10, sector: 'Financials', exchange: 'NSE' },
  { stockName: 'SBIN', symbol: 'SBIN.NS', purchasePrice: 600, quantity: 20, sector: 'Financials', exchange: 'NSE' },
  { stockName: 'ITC', symbol: 'ITC.NS', purchasePrice: 380, quantity: 50, sector: 'FMCG', exchange: 'NSE' },
  { stockName: 'HINDUNILVR', symbol: 'HINDUNILVR.NS', purchasePrice: 2600, quantity: 5, sector: 'FMCG', exchange: 'NSE' },
  { stockName: 'NESTLEIND', symbol: 'NESTLEIND.NS', purchasePrice: 21000, quantity: 1, sector: 'FMCG', exchange: 'NSE' },
  { stockName: 'TITAN', symbol: 'TITAN.NS', purchasePrice: 2800, quantity: 2, sector: 'Consumer', exchange: 'NSE' },
  { stockName: 'MARUTI', symbol: 'MARUTI.NS', purchasePrice: 9800, quantity: 1, sector: 'Auto', exchange: 'NSE' },
  { stockName: 'TATASTEEL', symbol: 'TATASTEEL.NS', purchasePrice: 130, quantity: 60, sector: 'Metals', exchange: 'NSE' },
  { stockName: 'JSWSTEEL', symbol: 'JSWSTEEL.NS', purchasePrice: 750, quantity: 7, sector: 'Metals', exchange: 'NSE' },
  { stockName: 'ADANIPORTS', symbol: 'ADANIPORTS.NS', purchasePrice: 1000, quantity: 3, sector: 'Infrastructure', exchange: 'NSE' },
  { stockName: 'DMART', symbol: 'DMART.NS', purchasePrice: 4000, quantity: 1, sector: 'Retail', exchange: 'NSE' },
  { stockName: 'LT', symbol: 'LT.NS', purchasePrice: 2400, quantity: 3, sector: 'Infrastructure', exchange: 'NSE' },
  { stockName: 'BHARTIARTL', symbol: 'BHARTIARTL.NS', purchasePrice: 850, quantity: 4, sector: 'Telecom', exchange: 'NSE' },
  { stockName: 'COALINDIA', symbol: 'COALINDIA.NS', purchasePrice: 250, quantity: 40, sector: 'Energy', exchange: 'NSE' },
  { stockName: 'ULTRACEMCO', symbol: 'ULTRACEMCO.NS', purchasePrice: 7500, quantity: 1, sector: 'Construction', exchange: 'NSE' },
  { stockName: 'AMBUJACEM', symbol: 'AMBUJACEM.NS', purchasePrice: 460, quantity: 10, sector: 'Construction', exchange: 'NSE' },
  { stockName: 'CIPLA', symbol: 'CIPLA.NS', purchasePrice: 1150, quantity: 6, sector: 'Pharma', exchange: 'NSE' },
  { stockName: 'SUNPHARMA', symbol: 'SUNPHARMA.NS', purchasePrice: 1100, quantity: 5, sector: 'Pharma', exchange: 'NSE' },
  { stockName: 'DIVISLAB', symbol: 'DIVISLAB.NS', purchasePrice: 3600, quantity: 2, sector: 'Pharma', exchange: 'NSE' },
  { stockName: 'HCLTECH', symbol: 'HCLTECH.NS', purchasePrice: 1150, quantity: 6, sector: 'Technology', exchange: 'NSE' },
  { stockName: 'TECHM', symbol: 'TECHM.NS', purchasePrice: 1100, quantity: 5, sector: 'Technology', exchange: 'NSE' },
  { stockName: 'POWERGRID', symbol: 'POWERGRID.NS', purchasePrice: 270, quantity: 20, sector: 'Utilities', exchange: 'NSE' },
];
